version: '3'
services:
  db:
    build:
      context: ./MySQL
    volumes:
      - "funko-datavolume:/var/lib/mysql"
      - "./MySQL/sql_files:/sql_files"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: funkoscrap
      MYSQL_USER: crawler
      MYSQL_PASSWORD: popopop
    container_name: golang_db
    ports:
      - "3307:3307"
    tty: true
  app:
    build:
      context: ./Go
    volumes:
      - "./Go:/go"
    container_name: golang_app
    ports:
      - "8080:8080"
    tty: true
    depends_on:
      - db
volumes:
  funko-datavolume: